apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flagd-kubernetes-sync
subjects:
- kind: ServiceAccount
  name: open-feature-operator-controller-manager
  namespace: system
  apiGroup: ""
- kind: ServiceAccount
  name: open-feature-operator-flagd-proxy
  namespace: system
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: open-feature-operator-flagd-kubernetes-sync
  apiGroup: ""