apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-proxy # matches the kubeProxyDeploymentName constant in pod_webhook
  namespace: system